#!/usr/bin/env bash
# SOURCE
# Usage: sub w {directoryname}
# Summary: A quick way to navigate to a repo inside your "workspace" location. 

# provide sub completions
dir=workspace
if [ ! -d $dir ]
then
    dir=Workspace
fi

if [ "$1" == "--complete" ]; then  
    ls ~/$dir
    exit
fi

cd ~/$dir/$1
