;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-paren
        c-electric-semi&comma
        evil-append-line
        evil-backward-char
        evil-change
        evil-change-line
        evil-copy-from-below
        evil-delete
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-force-normal-state
        evil-force-normal-state
        evil-forward-char
        evil-forward-word-begin
        evil-insert
        evil-normal-state
        evil-previous-line
        go-mode-insert-and-indent
        jedi:dot-complete
        tab-to-tab-stop
        viper-Append
        viper-backward-char
        viper-backward-word
        viper-beginning-of-line
        viper-command-argument
        viper-del-backward-char-in-insert
        viper-delete-char
        viper-digit-argument
        viper-forward-char
        viper-forward-word
        viper-goto-line
        viper-insert
        viper-intercept-ESC-key
        viper-previous-line
        viper-replace-char
        viper-scroll-up-one
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        mc/mark-next-lines
        ))
