;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        go-mode-insert-and-indent
        jedi:dot-complete
        viper-Append
        viper-backward-char
        viper-backward-word
        viper-beginning-of-line
        viper-del-backward-char-in-insert
        viper-delete-char
        viper-digit-argument
        viper-forward-char
        viper-forward-word
        viper-goto-line
        viper-insert
        viper-intercept-ESC-key
        viper-previous-line
        viper-scroll-up-one
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        mc/mark-next-lines
        ))
