;; (require 'helm-config)
;; (helm-mode 1)
;; (setq helm-idle-delay 0.01)
;; (setq helm-input-idle-delay 0.01)
;; (global-set-key (kbd "M-x") 'helm-M-x)
;; (global-set-key (kbd "C-x b") 'helm-mini)
;; (global-set-key (kbd "C-x C-f") 'helm-find-files)
;; (define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action)
